Lesson7
sasha370/stackoverflow pull request #10
Opened 2020-12-17 16:13 UTC by sasha370

2020-12-18 06:19 UTC, IvanShamatov requested changes
Добавь проверки на автора

2020-12-18 06:19 UTC, IvanShamatov commented on app/controllers/answers_controller.rb
> +    @answer.update(answer_params)
тут стоило бы проверить, что обновление делает пользователь, который этот ответ создавал

2020-12-18 06:19 UTC, IvanShamatov commented on app/views/answers/_answer.html.haml
> +  = form_with(model: answer, class: 'hidden', id: "edit_form_#{answer.id}"  )  do |form|
думаю этот блочек тоже стоит обернуть в `if current_user.author?(answer)`

2020-12-18 06:19 UTC, IvanShamatov commented on app/views/answers/create.js.erb
> +document.querySelector('#answer_body').innerText = '';
это айдишник инпута в котором давался новый ответ?

2020-12-18 06:19 UTC, IvanShamatov commented on spec/controllers/answers_controller_spec.rb
> +  describe "PATCH #update" do
тут как раз нет контекста, кто это делает, автор или не автор.

2020-12-18 09:45 UTC, sasha370 commented on app/views/answers/create.js.erb
> +document.querySelector('#answer_body').innerText = '';
Спасибо, в этом и была проблема. ID множился на каждую форму на странице и стирался первый

2020-12-18 10:22 UTC, sasha370 commented on spec/controllers/answers_controller_spec.rb
> +  describe "PATCH #update" do
b6610b5

2020-12-19 10:38 UTC, IvanShamatov commented on app/controllers/answers_controller.rb
> +    @answer.destroy if current_user.id == @answer.user_id
у тебя же есть метод author? зачем так-то?

2020-12-19 10:38 UTC, IvanShamatov commented on app/controllers/answers_controller.rb
> +    @answer.set_best if current_user.id == @answer.question.user_id
тоже самое, почему не используешь метод author?

2020-12-19 10:40 UTC, IvanShamatov commented on app/views/answers/_answer.html.haml
> +  - if current_user.present? && current_user.author?(answer)
избежать постоянных проверок на present? можно используя safe оператор

if current_user&.author?(...

2020-12-19 10:42 UTC, IvanShamatov commented on app/views/questions/show.html.haml
> +      - if @question.answers.any?
эта проверка лишняя, потому что если ответов нет, то и не отрендерится ничего

2020-12-19 13:09 UTC, merged