Lesson11 comet
sasha370/stackoverflow pull request #17
Opened 2021-01-07 13:12 UTC by sasha370

2021-01-11 18:45 UTC, IvanShamatov requested changes
Возвращаю на доработку

2021-01-11 18:45 UTC, IvanShamatov commented on app/controllers/answers_controller.rb
> +                                 html: html(@answer)
пожалуйста, возвращай json, а на фронте с помощью handlebars сделай шаблон, в котором будет очень похожая на текущий шаблон логика относительно current_user'a, 
current_user'a передавай с помощью gon'a

2021-01-11 18:45 UTC, IvanShamatov commented on app/controllers/answers_controller.rb
> +  def wardenize
не совсем представляю, как эта штука справится с тем, что множество разных пользователей будут видеть одну и ту же вьюшку, хотя current_user в них отличается.

2021-01-11 18:45 UTC, IvanShamatov commented on app/controllers/concerns/commented.rb
> +      render partial: 'comments/destroy_comment', layout: false
по идее на рендере и на редиректе выполнение обрывается, не думаю. что твой коммент удаляется, надо спеки глянуть

2021-01-11 18:45 UTC, IvanShamatov commented on app/controllers/questions_controller.rb
> +        content: { title: @question.title,
почему бы здесь весь объект не передать, или тебе достаточно только заголовка?

2021-01-11 18:45 UTC, IvanShamatov commented on app/javascript/channels/comments_channel.js
> +          if (gon.current_user_id != data.comment.user_id) {
можно сделать ксати guard clause, делать если это текущий пользователь, то return

2021-01-11 18:45 UTC, IvanShamatov commented on app/javascript/channels/question_channel.js
> +  } else if (/questions/.test(window.location.pathname) || /^\/$/.test(window.location.pathname) )  {
странно, почему ты сделал отдельный файл для комментов, а answers channel полжил внутрь question_channela

2021-01-11 18:45 UTC, IvanShamatov commented on app/javascript/channels/question_channel.js
> +        var template = Handlebars.compile(source);
темплейты нужно прекомпилировать, а не делать это каждый раз при получении очередного сообщения
И будет классно, если ты темплейты положишь в отдельный файлик (почти как компонент)

2021-01-11 18:45 UTC, IvanShamatov commented on app/views/answers/_answer.html.haml
> +              = link_to ' Edit |', '#', class: 'edit_link', id: "#{answer.id}"
странно, что у тебя сепаратор стал куском ссылки, верстальщики бы тебя за такое возненавидили

2021-01-11 18:45 UTC, IvanShamatov commented on spec/features/answer/create_spec.rb
> +        expect(page).to have_content 'Answer for question'
тут стоило бы проверить, а не появилась ли у второго пользователя ссылка на удаление или редактирование ответа

2021-01-11 18:45 UTC, IvanShamatov commented on spec/features/comment/create_spec.rb
> +        expect(page).to have_content 'My comment'
тут еще бы не помешала проверка, что второй коммент у пользователя не появился, мол один из аякса, другой из канала

2021-01-12 06:07 UTC, sasha370 commented on app/controllers/concerns/commented.rb
> +      render partial: 'comments/destroy_comment', layout: false
Все работало, но на всякий случай переставил строки

2021-01-12 06:08 UTC, sasha370 commented on app/controllers/questions_controller.rb
> +        content: { title: @question.title,
Да, для отрисовки достаточно только заголовка

2021-01-12 06:15 UTC, sasha370 commented on app/views/answers/_answer.html.haml
> +              = link_to ' Edit |', '#', class: 'edit_link', id: "#{answer.id}"
Увидел такой вариант на одном из зарубежных курсов))

2021-01-12 06:16 UTC, sasha370 commented on app/javascript/channels/question_channel.js
> +  } else if (/questions/.test(window.location.pathname) || /^\/$/.test(window.location.pathname) )  {
разнес по отдельным файлам.

2021-01-12 09:30 UTC, sasha370 commented on app/javascript/channels/comments_channel.js
> +          if (gon.current_user_id != data.comment.user_id) {
сделано

2021-01-12 12:18 UTC, sasha370 commented on app/controllers/answers_controller.rb
> +                                 html: html(@answer)
сделано

2021-01-12 12:19 UTC, sasha370 commented on app/controllers/answers_controller.rb
> +  def wardenize
я тоже не представляю, но о на работала)) 
У меня проблема была с установкой шаблонизатора, поэтому нашел такое решение.
Сейчас все удалил

2021-01-12 12:19 UTC, sasha370 commented on app/javascript/channels/question_channel.js
> +        var template = Handlebars.compile(source);
Исправлено, все переведено в шаблоны

2021-01-12 12:46 UTC, sasha370 commented on spec/features/answer/create_spec.rb
> +        expect(page).to have_content 'Answer for question'
Сделано

2021-01-12 12:46 UTC, sasha370 commented on spec/features/comment/create_spec.rb
> +        expect(page).to have_content 'My comment'
Сделано

2021-01-13 07:05 UTC, IvanShamatov approved these changes
Очень даже найс. только один коммент общий для нескольких файлов, поправь плз

2021-01-13 07:05 UTC, IvanShamatov commented on app/javascript/channels/answers_channel.js
> +        let template = require('./templates/answer.hbs')
еще раз, давай это где-то за пределами колбека делатЬ, нам темплейт нужно доставать только один раз, а не на каждое сообщение

2021-01-13 07:05 UTC, IvanShamatov commented on app/javascript/channels/comments_channel.js
> +          let template = require('./templates/comment.hbs')
см выше

2021-01-13 07:05 UTC, IvanShamatov commented on app/javascript/channels/question_channel.js
> +        let template = require('./templates/question.hbs')
та же самая шляпа. Зачем файл читать из раза в раз, это лишняя нагрузка

2021-01-13 11:10 UTC, merged